apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap  # name of ConfigMap, referenced in other files
  labels:
    #app: k8sdemo
data:
  MYSQL_HOST: mysql-service   # host address of mysql server, we are using DNS of Service
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: test # name of the database