apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    #app: k8sdemo
data:
  MYSQL_ROOT_PASSWORD: d3cwODE5Cg== # database password for "root"
  MYSQL_USER_NAME: d3NqCg==  # database user name for "dbuser"
  MYSQL_USER_PASSWORD: d3cwODE5Cg==  # database password for "dbuser"