apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    #app: k8sdemo-database
spec:
  type: NodePort
  selector:
    app: mysql-pod
  ports:
    - protocol : TCP
      nodePort: 30306
      port: 3306
      targetPort: 3306