apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort # 让请求能够从外部访问
  selector:
    app: nginx-pod # 把请求转发给带对应标签的pod
  ports:
    - nodePort: 30080 # 对外暴露的端口，本机通过localhost访问
      port: 81 # service的端
      targetPort: 80 # nginx pod的端口
